repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.9
    hooks:
      - id: uv-lock
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.411
    hooks:
      - id: pyright
  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.77
    hooks:
      - id: ty
