from collections.abc import Mapping, Sequence
from re import Pattern
from typing import AnyStr, Callable, Hashable, TypeVar, overload

from typing_extensions import ParamSpec, TypeAliasType

_P = ParamSpec("_P")
_T = TypeVar("_T")
_KT = TypeVar("_KT", bound=Hashable)
_VT = TypeVar("_VT")
_H = TypeVar("_H", bound=Hashable)

_RegexType = TypeAliasType(
    "_RegexType",
    AnyStr | Pattern[AnyStr],
    type_params=(AnyStr,),
)
_MatchType = TypeAliasType(
    "_MatchType",
    AnyStr | tuple[AnyStr, ...] | dict[str, AnyStr],
    type_params=(AnyStr,),
)

@overload
def all_fn(*fs: Callable[_P, object]) -> Callable[_P, bool]: ...
@overload
def all_fn(*fs: None) -> Callable[[object], bool]: ...
@overload
def all_fn(*fs: _RegexType[AnyStr]) -> Callable[[str], bool]: ...
@overload
def all_fn(*fs: int) -> Callable[[Sequence[object]], bool]: ...
@overload
def all_fn(*fs: slice) -> Callable[[Sequence[object]], bool]: ...
@overload
def all_fn(*fs: Mapping[_KT, _VT]) -> Callable[[_KT], bool]: ...
@overload
def all_fn(*fs: set[_H]) -> Callable[[_H], bool]: ...
@overload
def any_fn(*fs: Callable[_P, object]) -> Callable[_P, bool]: ...
@overload
def any_fn(*fs: None) -> Callable[[object], bool]: ...
@overload
def any_fn(*fs: _RegexType[AnyStr]) -> Callable[[str], bool]: ...
@overload
def any_fn(*fs: int) -> Callable[[Sequence[object]], bool]: ...
@overload
def any_fn(*fs: slice) -> Callable[[Sequence[object]], bool]: ...
@overload
def any_fn(*fs: Mapping[_KT, _VT]) -> Callable[[_KT], bool]: ...
@overload
def any_fn(*fs: set[_H]) -> Callable[[_H], bool]: ...
@overload
def none_fn(*fs: Callable[_P, object]) -> Callable[_P, bool]: ...
@overload
def none_fn(*fs: None) -> Callable[[object], bool]: ...
@overload
def none_fn(*fs: _RegexType[AnyStr]) -> Callable[[str], bool]: ...
@overload
def none_fn(*fs: int) -> Callable[[Sequence[object]], bool]: ...
@overload
def none_fn(*fs: slice) -> Callable[[Sequence[object]], bool]: ...
@overload
def none_fn(*fs: Mapping[_KT, _VT]) -> Callable[[_KT], bool]: ...
@overload
def none_fn(*fs: set[_H]) -> Callable[[_H], bool]: ...
@overload
def one_fn(*fs: Callable[_P, object]) -> Callable[_P, bool]: ...
@overload
def one_fn(*fs: None) -> Callable[[object], bool]: ...
@overload
def one_fn(*fs: _RegexType[AnyStr]) -> Callable[[str], bool]: ...
@overload
def one_fn(*fs: int) -> Callable[[Sequence[object]], bool]: ...
@overload
def one_fn(*fs: slice) -> Callable[[Sequence[object]], bool]: ...
@overload
def one_fn(*fs: Mapping[_KT, _VT]) -> Callable[[_KT], bool]: ...
@overload
def one_fn(*fs: set[_H]) -> Callable[[_H], bool]: ...
@overload
def some_fn(*fs: Callable[_P, _T]) -> Callable[_P, _T | None]: ...
@overload
def some_fn(*fs: None) -> Callable[[_T], _T | None]: ...
@overload
def some_fn(
    *fs: _RegexType[AnyStr],
) -> Callable[[str], _MatchType[AnyStr] | None]: ...
@overload
def some_fn(*fs: int) -> Callable[[Sequence[_T]], _T | None]: ...
@overload
def some_fn(*fs: slice) -> Callable[[Sequence[_T]], Sequence[_T] | None]: ...
@overload
def some_fn(*fs: Mapping[_KT, _VT]) -> Callable[[_KT], _VT | None]: ...
@overload
def some_fn(*fs: set[_H]) -> Callable[[_H], bool | None]: ...

__all__ = ["all_fn", "any_fn", "none_fn", "one_fn", "some_fn"]
