from typing import Callable

from ._types import B, Boolean, P

def all_fn(*fs: Callable[P, Boolean[B]]) -> B: ...
def any_fn(*fs: Callable[P, Boolean[B]]) -> B: ...
def none_fn(*fs: Callable[P, Boolean[B]]) -> B: ...
def one_fn(*fs: Callable[P, Boolean[B]]) -> B: ...
def some_fn(*fs: Callable[P, Boolean[B]]) -> B: ...

__all__ = ("all_fn", "any_fn", "none_fn", "one_fn", "some_fn")
