from collections.abc import Mapping, Sequence
from typing import AnyStr, Callable, overload

from ._types import KT, VT, H, MatchType, P, RegexType, T

@overload
def all_fn(*fs: Callable[P, object]) -> Callable[P, bool]: ...
@overload
def all_fn(*fs: None) -> Callable[[object], bool]: ...
@overload
def all_fn(*fs: RegexType[AnyStr]) -> Callable[[str], bool]: ...
@overload
def all_fn(*fs: int) -> Callable[[Sequence[object]], bool]: ...
@overload
def all_fn(*fs: slice) -> Callable[[Sequence[object]], bool]: ...
@overload
def all_fn(*fs: Mapping[KT, VT]) -> Callable[[KT], bool]: ...
@overload
def all_fn(*fs: set[H]) -> Callable[[H], bool]: ...
@overload
def any_fn(*fs: Callable[P, object]) -> Callable[P, bool]: ...
@overload
def any_fn(*fs: None) -> Callable[[object], bool]: ...
@overload
def any_fn(*fs: RegexType[AnyStr]) -> Callable[[str], bool]: ...
@overload
def any_fn(*fs: int) -> Callable[[Sequence[object]], bool]: ...
@overload
def any_fn(*fs: slice) -> Callable[[Sequence[object]], bool]: ...
@overload
def any_fn(*fs: Mapping[KT, VT]) -> Callable[[KT], bool]: ...
@overload
def any_fn(*fs: set[H]) -> Callable[[H], bool]: ...
@overload
def none_fn(*fs: Callable[P, object]) -> Callable[P, bool]: ...
@overload
def none_fn(*fs: None) -> Callable[[object], bool]: ...
@overload
def none_fn(*fs: RegexType[AnyStr]) -> Callable[[str], bool]: ...
@overload
def none_fn(*fs: int) -> Callable[[Sequence[object]], bool]: ...
@overload
def none_fn(*fs: slice) -> Callable[[Sequence[object]], bool]: ...
@overload
def none_fn(*fs: Mapping[KT, VT]) -> Callable[[KT], bool]: ...
@overload
def none_fn(*fs: set[H]) -> Callable[[H], bool]: ...
@overload
def one_fn(*fs: Callable[P, object]) -> Callable[P, bool]: ...
@overload
def one_fn(*fs: None) -> Callable[[object], bool]: ...
@overload
def one_fn(*fs: RegexType[AnyStr]) -> Callable[[str], bool]: ...
@overload
def one_fn(*fs: int) -> Callable[[Sequence[object]], bool]: ...
@overload
def one_fn(*fs: slice) -> Callable[[Sequence[object]], bool]: ...
@overload
def one_fn(*fs: Mapping[KT, VT]) -> Callable[[KT], bool]: ...
@overload
def one_fn(*fs: set[H]) -> Callable[[H], bool]: ...
@overload
def some_fn(*fs: Callable[P, T]) -> Callable[P, T | None]: ...
@overload
def some_fn(*fs: None) -> Callable[[T], T | None]: ...
@overload
def some_fn(
    *fs: RegexType[AnyStr],
) -> Callable[[str], MatchType[AnyStr] | None]: ...
@overload
def some_fn(*fs: int) -> Callable[[Sequence[T]], T | None]: ...
@overload
def some_fn(*fs: slice) -> Callable[[Sequence[T]], Sequence[T] | None]: ...
@overload
def some_fn(*fs: Mapping[KT, VT]) -> Callable[[KT], VT | None]: ...
@overload
def some_fn(*fs: set[H]) -> Callable[[H], bool | None]: ...

__all__ = ("all_fn", "any_fn", "none_fn", "one_fn", "some_fn")
