from typing import Any, Protocol, TypeVar

from typing_extensions import TypeGuard

_T_co = TypeVar("_T_co", covariant=True)

class _SupportPlus(Protocol[_T_co]):
    def __add__(self, value: int, /) -> _T_co: ...

class _SupportMinus(Protocol[_T_co]):
    def __sub__(self, value: int, /) -> _T_co: ...

class _SupportMod(Protocol):
    def __mod__(self, value: int, /) -> int: ...

def isnone(x: Any) -> TypeGuard[None]: ...
def notnone(x: Any) -> bool: ...
def inc(x: _SupportPlus[_T_co]) -> _T_co: ...
def dec(x: _SupportMinus[_T_co]) -> _T_co: ...
def even(x: _SupportMod) -> bool: ...
def odd(x: _SupportMod) -> bool: ...

__all__ = ["dec", "even", "inc", "isnone", "notnone", "odd"]
