from collections.abc import Iterable, Iterator
from typing import Callable, TypeVar

from typing_extensions import TypeAliasType

_T = TypeVar("_T")

_Follow = TypeAliasType("_Follow", Callable[[_T], bool], type_params=(_T,))
_Children = TypeAliasType("_Children", Callable[[_T], Iterator[_T]], type_params=(_T,))

def tree_leaves(
    root: _T, follow: _Follow[_T] = ..., children: _Children[_T] = ...
) -> Iterable[_T]: ...
def ltree_leaves(
    root: _T, follow: _Follow[_T] = ..., children: _Children[_T] = ...
) -> list[_T]: ...
def tree_nodes(
    root: _T, follow: _Follow[_T] = ..., children: _Children[_T] = ...
) -> Iterable[_T]: ...
def ltree_nodes(
    root: _T, follow: _Follow[_T] = ..., children: _Children[_T] = ...
) -> list[_T]: ...

__all__ = ["ltree_leaves", "ltree_nodes", "tree_leaves", "tree_nodes"]
